### ISSUE TITLE
Edit functionality

### ISSUE THREAD

**Issue by kitzberger** [abzubarev/web-developer-form-filler-ext#22]
Thanks for a really helpful tool!

Would be cool to be able to edit the sets (especially the domain pattern!) without having to export, modify the JSON and re-import it afterwards.

**Comment by abzubarev** [comment]
Make sure you have the latest version and try the new Edit button
Let me know if it worked for you

![image](https://user-images.githubusercontent.com/5098318/118011770-17f00800-b359-11eb-8d24-20ce72417bad.png)
