### ISSUE TITLE
Can not donate 

### ISSUE THREAD

**Issue by chrishaensel** [abzubarev/web-developer-form-filler-ext#24]
I just wanted to donate, but when I reach Paypal, it gives me this error:

We cannot process this transaction because this PayPal account has been closed. For more information, please contact the seller.

Cheers

Chris

**Comment by ravindrasinghinbox** [comment]
Hi, You can send to me also. I'm also developer :)

**Comment by abzubarev** [comment]
@chrishaensel Thanks! Updated in recent version

**Comment by chrishaensel** [comment]
Thanks @abzubarev.

**Comment by abzubarev** [comment]
@chrishaensel I got it, thanks you!
