### ISSUE TITLE
Random fragments

### ISSUE THREAD

**Issue by GriffinSauce** [abzubarev/web-developer-form-filler-ext#27]
It could be very useful to have a random fragment in output. That way a signup form can be tested without having to add some random stuff to the email/username. It could also help to differentiate test users by first name for example.

Implementation idea: On deserialisation, replace `%RANDOM%` keyword with a (pseudo)randomised string, limited to HEX is probably safest. This doesn't require any extra UI (except perhaps a hint in the popup).

Input: `user+%RANDOM%@test.com`
Output: `user+F35S234DFF34@test.com`

I'd be willing to try a PR for this if you like the idea.

**Comment by l00k** [comment]
#32 created

**Comment by abzubarev** [comment]
Added in recent version
