### ISSUE TITLE
Error handling response: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by KoalaBear84** [abzubarev/web-developer-form-filler-ext#31]
I'm getting this on every page in the console. Because it is minified I don't know what variable it is.

```
Error handling response: TypeError: Cannot read property 'replace' of undefined
    at F (chrome-extension://gbagmkohmhcjgbepncmehejaljoclpil/javascripts/mousetrap.min.js:5:378)
    at Object.bind (chrome-extension://gbagmkohmhcjgbepncmehejaljoclpil/javascripts/mousetrap.min.js:7:488)
    at chrome-extension://gbagmkohmhcjgbepncmehejaljoclpil/javascripts/content_script.js:85:19
```

Screenshot:
![image](https://user-images.githubusercontent.com/5886900/55712934-f42a9d00-59ef-11e9-8ee1-6e3008e056c0.png)

**Comment by KoalaBear84** [comment]
Any news?

**Comment by abzubarev** [comment]
Whats your hotkey settings?

**Comment by gebilaoman** [comment]
metoo

**Comment by KoalaBear84** [comment]
Looks like I didn't received the notification of your reply. I'm not sure what the question is about, I don't see any options about it.

Also don't see this error anymore, but it's also 2.5 years later :)
