### ISSUE TITLE
extension not work in chrome with new update !!!

### ISSUE THREAD

**Issue by varta2014** [abzubarev/web-developer-form-filler-ext#33]
hi 
chrome not work after update 9 May 2021 Version 1.0.13.1
please help thanks

**Comment by abzubarev** [comment]
Any errors in console?

**Comment by varta2014** [comment]
when we click to restore there is no response

**Comment by abzubarev** [comment]
It's not enough information to address your issue

Provide screenshots, a video or console output

**Comment by varta2014** [comment]
hotkeys + restore in yellow not respone no result !
https://c.radikal.ru/c18/2105/09/37e48f741396.png

**Comment by abzubarev** [comment]
Can you send me your JSON for the page?

![image](https://user-images.githubusercontent.com/5098318/118015644-2fc98b00-b35d-11eb-86b5-28a5ae6cdaf3.png)

**Comment by varta2014** [comment]
oh you right its work in other sites just mine :(
i give you to check but site is private 

{"url":"https://private site/-/edit/","autoSubmit":false,"submitQuery":"","content":"{\"id_promo\":\"test to github\",\"id_no_imdb\":\"false\",\"id_languages\":[\"1\"],\"id_show_in_home\":\"true\"}","name":785078654,"hotkey":""}
